travis:
  secure:
    BINSTAR_TOKEN: qgQWbbFFtlomy3ev4MBe6ly5g7cOSar45UONXowDb1n58fZhhyHF1Tgnw6ywArawDhjnLE/Nfdn7jZ48ik0k0pJBpJvvMw4AH3Z8gEIfKoyu8UPpm6YGv1vsu8fDGXVT1dIAoUDKnQGlRHYojAb1hopFHCm6jzcxuPokOi2xVdRgyD1hTbz2AKIp9JF0ww5M8KepDTm++ZmRDpKggRNE5wFRSiAxcDqdExrBK7IMosVixrNu/9Q7PhGYOmkcKHYvLyU6hcA7CnssLfh//3FawSDaQkQp9bx0LnL7dqDiADxcNCaXsDwLDTdlq3E2iPZS0OuM3RcnDoflFpi5vf5dHKLteaXaoxT2WmQhes0tn6MkwagJEQzNsTCbZnm4cMFY7ESd3/xiqEiYEUz0mAQS3Qrxu6vRa/15BZyfmnoF63zXXCKN/PRMRXIlJgnMGL55RiS9Nm8+2Cbhb2M9DrhKFKJwj+dU7oDD8mOwUPk9i8J3Kf9XwKOXRA/2kK9a2Q4ATDriGeGL48ayKc8iEW+1MaAn6oN7/qvoU3Q51eaidK8T8HNC212+O+o7qoyyEbGJZeiJXY36Oc1od1PZ2VobzeRg9FYxNbyFU2MtJs6aG1auPat11nj2lSNqJmoBjWIaKzQGEOTCCG3GVXQEOuPmjnKyWcoL4DvhsQt65DlUSEo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
