travis:
  secure:
    BINSTAR_TOKEN: KPxkij+s3wtGBQLkyMgiD8BhVolPpQdlt52WVBlPOfJBtL9QE2oP1l7Lb1ULsUWUkGvPBUCOIDxuWgh84DdWRcfMUaSQxhyjqqX9kNsCa7pL575/g2eP5PNSikH3suubIwVeQOQUjTeEEvdBPoyy2Nw14GeioHTiJMD9bTEOezmV0ijVBXd/V+K4dKpkqSdwEsfhX9VRWM4oQOmqzHyLlljDV9f5+1Hj/Acegbl6XCyI69B/KCYisj2ZWsA16cLyNM4d+bYC88AVyosofjGGmG6+97V7PdFf1OCAABYmu64yBg0Sg3DIxXdAFAknccg/5tIOvBwIrpHVf6jdwicFMP7ntbkdq7nz0gE9IV4fAselKVe7358cp018cZD12htQ5xNjrycWUMseFD79vJKRsixKapdf3gaWqZP3yV6Bx3oXFe8F9uYDzZW9Ue5rFQsgDwDfeLzGEnS5aVIMovniup7qrfc+hgEBdph2OMptan3Iy1ie+fq233TEwhJVPLtpqu6T1k0h1LCFLRDUfYxmcJl/dh916VJEk9FSf+3AjkqcdRPPxxXV56SIywFNTa6HA76rScH88fXTjUlER8M2XUzSUuulMokPZJjWgS7FS5eX9QbCcOCQeRi4aWBRUMQw+kyAqDnWLqqzwUcm5mPXWLXNDzITlrK4u38LNyohOcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
